name: quotes
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Default icons asset for Cupertino widgets based on Apple styled icons
  cupertino_icons: ^1.0.6
  # A powerful HTTP networking package, supports Interceptors, Aborting and canceling a request
  dio: ^5.4.2+1
  # state management Bloc (Business Logic Component) design pattern. Built to be used with the bloc state management package
  flutter_bloc: ^8.1.5
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5
  # Easily create toast messages in single line of code
  fluttertoast: ^8.2.4
  # Flutter widgets for easily adding gaps inside Flex widgets such as Columns and Rows or scrolling views.
  gap: ^3.0.1
  # Functional Programming in Dart. Purify your Dart code using efficient immutable data structures, monads, lenses and other FP tools
  dartz: ^0.10.1
  # check your internet connection with subsecond response times, even on mobile networks!
  #  internet_connection_checker_plus: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  # for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.2.2
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^7.6.8
  #  Loading animation. It's used to show loading animation when the app is in loading state or something is processing for uncertain time.
  loading_animation_widget: ^1.2.1
  # Logger. Easy, customizable, extensible logging, lightweight with filters, formatters, custom logs, log levels.
  talker_logger: ^4.1.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  flutter_lints: ^3.0.2


analyzer:
  plugins:
    - custom_lint

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900



